<?php

function gallery_content_type_theme($existing, $type, $theme, $path) {
    
    return [
        'node__gallery_item' => [
          'template' => 'node--gallery-item',
          'base hook' => 'node',
        ],
        'node__gallery_item__teaser' => [
          'template' => 'node--gallery-item--teaser',
          'base hook' => 'node',
        ],
      ];
    
}









function gallery_content_type_preprocess_node(&$variables) {
    
    // Get statistics count for current node. Statistics module must be enabled.
    $statistics = statistics_get($variables['node']->id());
    $variables['node_stats'] = \Drupal::translation()->formatPlural($statistics['totalcount'], '1 view', '@count views');
    
    $config = \Drupal::config('gallery_content_type.gallery_content_type_settings');
    $variables['showNodeAuthor'] = $config->get('show_node_author');
    $variables['showNodeDetails'] = $config->get('show_node_details');
    $variables['showGalleryOptionBar'] = $config->get('show_gallery_option_bar');
    $variables['showNodeTeaserAuthor'] = $config->get('show_node_teaser_author');
    $variables['showNodeTeaserPublish'] = $config->get('show_node_teaser_publish');
    
}

?>