<?php

function gallery_content_type_theme($existing, $type, $theme, $path) {
    
    return [
        'node__gallery_item' => [
          'template' => 'node--gallery-item',
          'base hook' => 'node',
        ],
        'node__gallery_item__teaser' => [
          'template' => 'node--gallery-item--teaser',
          'base hook' => 'node',
        ],
      ];
    
}









function gallery_content_type_preprocess_node(&$variables) {
    
    // Get statistics count for current node. Statistics module must be enabled.
    $statistics = statistics_get($variables['node']->id());
    $variables['node_stats'] = \Drupal::translation()->formatPlural($statistics['totalcount'], '1 view', '@count views');
   
    $variables['#attached']['library'][] = 'gallery_content_type/styles';
    $variables['module_path'] = \Drupal::moduleHandler()->getModule('gallery_content_type')->getPath();
    
    $config = \Drupal::config('gallery_content_type.gallery_content_type_settings');
    $variables['showUser'] = $config->get('show_user');
    $variables['showDetails'] = $config->get('show_details');
    
}

?>